[tripleo-heat-agents] Install testrepository
This is required for running the unit tests for the
project tripleo-heat-agents:

"/usr/bin/bash: line 1: testr: command not found"

In addition, re-installation of setuptools is required to
avoid this error:

AttributeError: module 'pkg_resources' has no attribute 'Requirement'